### ISSUE TITLE
Invalid characters on category name (colon)

### ISSUE THREAD

**Issue by rfdrake** [OpenNMS/onmsctl#21]
I tried dumping my existing requisition and then re-importing it and got this error.  Here is what I did:

    onmsctl inv req get myrequisition > req.yaml
    onmsctl inv req apply -f req.yaml

    ERROR: Problem on node test on requisition myrequisition: Invalid characters on category name Site:mysite:, /, \, ?, &, *, ', "

I thought this might be a quoting issue so I tried putting quotes around the offending category, but it had the same issue.  If I delete the "Site:site" category it can import.

```
name: myrequisition
nodes:
- nodeLabel: test
  foreignID: "5408"
  building: SITE
  interfaces:
  - ipAddress: 10.1.0.1
    snmpPrimary: P
    status: 1
    services:
    - name: ICMP
  categories:
  - name: Switches
  - name: Production
  - name: "Site:site"
  - name: Alerts1M
```

I removed the colon from the regexp and it imported my test file.  I don't know if doing this will cause anyone else problems though.
